### PR TITLE
302 Added api to show blockspan 

### LINKED ISSUE #302: Update the blockspan view to use overlaping blockheight in blockspan
http://dev-exchange.op-energy.info/hashstrikes/blockspans/1/766932

Currently, blockspan views are incorrect the block height should be overlapped.

For e.g:

Block Span 1: 31, 32
Block Span 2: 32, 33
Block Span 3: 33,34 ... like wise

### PR DESCRIPTION
**Pull request by Natsvora**
302 Added API to show blockspan

### CODE REVIEW

File: frontend/src/app/oe/interfaces/op-energy.interface.ts [hunk 1]
```diff
@@ -50,3 +50,8 @@ export interface NavigationObject {
     },
   },
 }
+
+export interface BlockHeights {
```
Comment (dambaev) [inline frontend/src/app/oe/interfaces/op-energy.interface.ts]: BlockHeights is wrong name here: BlockHeights means list of BlockHeight. It seems, that it should be BlockSpan instead, as in the backend

**Review by dambaev — CHANGES_REQUESTED** [review]

**Review by dambaev — APPROVED** [review]
